//! Rust-native wrapper and registry generator for SynStream plugins.
//!
//! Parses a Rust source file and produces two generated files:
//!
//! - `wrappers.rs` – `cache_sym!` statics + `_wrap` functions for each exported function.
//! - `func_reg.rs` – `get_func` registry mapping string names → `CmPtr`.
//!
//! Two kinds of source annotations are recognised:
//!
//! 1. `#[no_mangle] pub fn` – these are already the `_cm` bridge functions.
//!    The converter reads their actual types directly.
//!
//! 2. `#[synstream_export] pub fn` – these are the original domain functions.
//!    The converter infers the `_cm` signature using the same classification
//!    logic as the proc-macro in `synstream-macro`.

use std::path::Path;

use syn::{
    Attribute, FnArg, File, Item, ItemFn, Pat, PatType, ReturnType, Type, TypePath,
    TypeReference, parse_str,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Parse `input_path`, then write `wrappers_output` and `registry_output`.
///
/// # Errors
///
/// Returns an error if the input cannot be read or parsed, or if writing
/// either output file fails.
pub fn generate_from_file(
    input_path: &Path,
    wrappers_output: &Path,
    registry_output: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let source = std::fs::read_to_string(input_path)
        .map_err(|e| format!("cannot read {}: {}", input_path.display(), e))?;

    let ast: File =
        parse_str(&source).map_err(|e| format!("cannot parse {}: {}", input_path.display(), e))?;

    let entries = collect_entries(&ast);

    let wrappers_code = render_wrappers(&entries);
    let registry_code = render_registry(&entries);

    std::fs::write(wrappers_output, wrappers_code)
        .map_err(|e| format!("cannot write {}: {}", wrappers_output.display(), e))?;
    std::fs::write(registry_output, registry_code)
        .map_err(|e| format!("cannot write {}: {}", registry_output.display(), e))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Data model
// ---------------------------------------------------------------------------

/// A single exported function, with the `_cm` signature already resolved.
#[derive(Debug)]
struct ExportedFn {
    /// The `_cm` function name (e.g. `generate_vector_cm`).
    cm_name: String,
    /// The registry key (e.g. `"generate_vector"`).
    registry_key: String,
    /// Parameters as they appear in the **`_cm` function** signature.
    cm_params: Vec<CmParam>,
    /// Return type of the `_cm` function.
    cm_ret: CmRet,
}

/// A parameter as seen in the `_cm` function.
#[derive(Debug, Clone)]
struct CmParam {
    name: String,
    kind: CmParamKind,
}

/// How a `_cm` parameter should be extracted from `args: &[CmTypes]`.
#[derive(Debug, Clone)]
enum CmParamKind {
    /// `&CmTypes` — pass `&args[i]` directly.
    CmTypesRef,
    /// A primitive whose `CmTypes` variant is known.
    Primitive(PrimKind),
    /// `&str` — extract from `CmTypes::String`.
    StrRef,
    /// Owned `String` — extract from `CmTypes::String`.
    OwnedString,
    /// `&Vec<CmTypes>` — collect `args[i..]`.
    VecCmTypes,
    /// `&[CmTypes]` — pass `&args[i..]` directly (generated by `variadic` macro).
    SliceCmTypes,
}

#[derive(Debug, Clone)]
enum PrimKind {
    Bool,
    I8,
    I16,
    I32,
    I64,
    I128,
    U8,
    U16,
    U32,
    U64,
    U128,
    F32,
    F64,
    Usize,
    Isize,
    Char,
}

impl PrimKind {
    fn variant_name(&self) -> &'static str {
        match self {
            PrimKind::Bool => "Bool",
            PrimKind::I8 => "I8",
            PrimKind::I16 => "I16",
            PrimKind::I32 => "I32",
            PrimKind::I64 => "I64",
            PrimKind::I128 => "I128",
            PrimKind::U8 => "U8",
            PrimKind::U16 => "U16",
            PrimKind::U32 => "U32",
            PrimKind::U64 => "U64",
            PrimKind::U128 => "U128",
            PrimKind::F32 => "F32",
            PrimKind::F64 => "F64",
            PrimKind::Usize => "Usize",
            PrimKind::Isize => "Isize",
            PrimKind::Char => "Char",
        }
    }

    fn rust_type(&self) -> &'static str {
        match self {
            PrimKind::Bool => "bool",
            PrimKind::I8 => "i8",
            PrimKind::I16 => "i16",
            PrimKind::I32 => "i32",
            PrimKind::I64 => "i64",
            PrimKind::I128 => "i128",
            PrimKind::U8 => "u8",
            PrimKind::U16 => "u16",
            PrimKind::U32 => "u32",
            PrimKind::U64 => "u64",
            PrimKind::U128 => "u128",
            PrimKind::F32 => "f32",
            PrimKind::F64 => "f64",
            PrimKind::Usize => "usize",
            PrimKind::Isize => "isize",
            PrimKind::Char => "char",
        }
    }
}

/// Return kind of the `_cm` function.
#[derive(Debug, Clone)]
enum CmRet {
    /// The `_cm` function is void (`fn(...)` with no return).  The `_wrap`
    /// function calls it and then returns `CmTypes::None`.
    Void,
    /// Returns `CmTypes` directly.
    CmTypes,
    /// Returns a primitive (needs wrapping into a `CmTypes::Variant`).
    Primitive(PrimKind),
    /// Returns `String` (needs `CmTypes::String(Arc::from(...))`).
    OwnedString,
}

// ---------------------------------------------------------------------------
// Type classification helpers
// ---------------------------------------------------------------------------

fn prim_kind_from_str(name: &str) -> Option<PrimKind> {
    match name {
        "bool" => Some(PrimKind::Bool),
        "i8" => Some(PrimKind::I8),
        "i16" => Some(PrimKind::I16),
        "i32" => Some(PrimKind::I32),
        "i64" => Some(PrimKind::I64),
        "i128" => Some(PrimKind::I128),
        "u8" => Some(PrimKind::U8),
        "u16" => Some(PrimKind::U16),
        "u32" => Some(PrimKind::U32),
        "u64" => Some(PrimKind::U64),
        "u128" => Some(PrimKind::U128),
        "f32" => Some(PrimKind::F32),
        "f64" => Some(PrimKind::F64),
        "usize" => Some(PrimKind::Usize),
        "isize" => Some(PrimKind::Isize),
        "char" => Some(PrimKind::Char),
        _ => None,
    }
}

fn is_primitive_ident(name: &str) -> bool {
    prim_kind_from_str(name).is_some()
}

fn type_path_ident(ty: &Type) -> Option<String> {
    if let Type::Path(TypePath { qself: None, path }) = ty {
        if path.segments.len() == 1 {
            return Some(path.segments[0].ident.to_string());
        }
        // Multi-segment: return last segment
        return path.segments.last().map(|s| s.ident.to_string());
    }
    None
}

fn ref_is_str(r: &TypeReference) -> bool {
    if let Type::Path(TypePath { qself: None, path }) = r.elem.as_ref() {
        path.segments.len() == 1 && path.segments[0].ident == "str"
    } else {
        false
    }
}

fn ref_is_cm_types(r: &TypeReference) -> bool {
    type_path_ident(r.elem.as_ref())
        .map(|n| n == "CmTypes")
        .unwrap_or(false)
}

/// Check if `&[CmTypes]` (generated by `variadic` macro attribute).
fn ref_is_slice_cm_types(r: &TypeReference) -> bool {
    if let Type::Slice(slice) = r.elem.as_ref() {
        type_path_ident(&slice.elem)
            .map(|n| n == "CmTypes")
            .unwrap_or(false)
    } else {
        false
    }
}

/// Check if `&Vec<CmTypes>` (last variadic parameter).
fn ref_is_vec_cm_types(r: &TypeReference) -> bool {
    if let Type::Path(TypePath { qself: None, path }) = r.elem.as_ref() {
        if path.segments.len() == 1 && path.segments[0].ident == "Vec" {
            if let syn::PathArguments::AngleBracketed(ab) = &path.segments[0].arguments {
                if ab.args.len() == 1 {
                    if let syn::GenericArgument::Type(inner) = &ab.args[0] {
                        return type_path_ident(inner).map(|n| n == "CmTypes").unwrap_or(false);
                    }
                }
            }
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Classifying `_cm` parameters (from actual `#[no_mangle]` signature)
// ---------------------------------------------------------------------------

fn classify_cm_param(ty: &Type) -> CmParamKind {
    match ty {
        Type::Reference(r) => {
            if ref_is_str(r) {
                CmParamKind::StrRef
            } else if ref_is_cm_types(r) {
                CmParamKind::CmTypesRef
            } else if ref_is_slice_cm_types(r) {
                CmParamKind::SliceCmTypes
            } else if ref_is_vec_cm_types(r) {
                CmParamKind::VecCmTypes
            } else {
                // Unknown ref — treat as CmTypesRef (safe fallback)
                CmParamKind::CmTypesRef
            }
        }
        Type::Path(_) => {
            let name = type_path_ident(ty).unwrap_or_default();
            if let Some(pk) = prim_kind_from_str(&name) {
                CmParamKind::Primitive(pk)
            } else if name == "String" {
                CmParamKind::OwnedString
            } else if name == "CmTypes" {
                // Owned CmTypes — pass directly
                CmParamKind::CmTypesRef
            } else {
                CmParamKind::CmTypesRef
            }
        }
        _ => CmParamKind::CmTypesRef,
    }
}

// ---------------------------------------------------------------------------
// Classifying return type of `_cm` functions
// ---------------------------------------------------------------------------

fn classify_cm_return(ret: &ReturnType) -> CmRet {
    match ret {
        ReturnType::Default => CmRet::Void, // void → _wrap returns CmTypes::None
        ReturnType::Type(_, ty) => {
            let name = type_path_ident(ty).unwrap_or_default();
            match name.as_str() {
                "CmTypes" => CmRet::CmTypes,
                "String" => CmRet::OwnedString,
                other => {
                    if let Some(pk) = prim_kind_from_str(other) {
                        CmRet::Primitive(pk)
                    } else {
                        // Assume the function returns CmTypes (common case for _cm functions)
                        CmRet::CmTypes
                    }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Inferring `_cm` parameter types from `#[synstream_export]` original signature
// ---------------------------------------------------------------------------

/// Given a parameter type from the *original* (non-`_cm`) function, infer
/// what the `_cm` counterpart parameter type and extraction kind would be.
fn infer_cm_param_kind(ty: &Type) -> CmParamKind {
    match ty {
        Type::Reference(r) => {
            if ref_is_str(r) {
                // `&str` → keep as `&str` in `_cm`, extract from String
                CmParamKind::StrRef
            } else {
                // `&T` or `&mut T` for non-primitive → `&CmTypes`
                CmParamKind::CmTypesRef
            }
        }
        Type::Path(_) => {
            let name = type_path_ident(ty).unwrap_or_default();
            if is_primitive_ident(&name) || name == "String" {
                // Primitive or String — passthrough in `_cm`
                if name == "String" {
                    CmParamKind::OwnedString
                } else if let Some(pk) = prim_kind_from_str(&name) {
                    CmParamKind::Primitive(pk)
                } else {
                    CmParamKind::CmTypesRef
                }
            } else {
                // Owned non-primitive → `&CmTypes`
                CmParamKind::CmTypesRef
            }
        }
        _ => CmParamKind::CmTypesRef,
    }
}

/// Infer return kind for `_cm` from the original function return type.
fn infer_cm_return(ret: &ReturnType) -> CmRet {
    // The proc-macro ALWAYS generates a `_cm` that returns `-> CmTypes`.
    // So regardless of whether the original function is void, returns a primitive,
    // returns String, or returns an opaque type, the companion `_cm` symbol always
    // has `-> CmTypes` in its signature.
    match ret {
        ReturnType::Default => CmRet::CmTypes, // void original → _cm returns CmTypes::None
        ReturnType::Type(_, ty) => {
            let name = type_path_ident(ty).unwrap_or_default();
            match name.as_str() {
                "CmTypes" => CmRet::CmTypes,
                // All other return types (String, primitives, opaque) → the proc-macro
                // wraps them into CmTypes, so the _cm symbol still returns CmTypes.
                _ => CmRet::CmTypes,
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Attribute helpers
// ---------------------------------------------------------------------------

fn has_attr(attrs: &[Attribute], name: &str) -> bool {
    attrs.iter().any(|a| {
        let path = a.path();
        path.segments.last().map(|s| s.ident == name).unwrap_or(false)
    })
}

/// Returns true if `#[synstream_export(variadic)]` is present.
fn has_variadic_export(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        let is_export = a.path().segments.last()
            .map(|s| s.ident == "synstream_export")
            .unwrap_or(false);
        if !is_export { return false; }
        // Check if the attribute tokens contain "variadic"
        matches!(a.meta, syn::Meta::List(_)) && {
            if let syn::Meta::List(ref ml) = a.meta {
                ml.tokens.to_string().contains("variadic")
            } else {
                false
            }
        }
    })
}

fn extract_param_name(arg: &FnArg) -> Option<String> {
    if let FnArg::Typed(PatType { pat, .. }) = arg {
        if let Pat::Ident(pi) = pat.as_ref() {
            return Some(pi.ident.to_string());
        }
    }
    None
}

fn extract_param_type(arg: &FnArg) -> Option<&Type> {
    if let FnArg::Typed(PatType { ty, .. }) = arg {
        Some(ty.as_ref())
    } else {
        None
    }
}

// ---------------------------------------------------------------------------
// Collecting entries from the AST
// ---------------------------------------------------------------------------

fn collect_entries(file: &File) -> Vec<ExportedFn> {
    let mut entries = Vec::new();

    for item in &file.items {
        if let Item::Fn(func) = item {
            if let Some(entry) = try_extract(func) {
                entries.push(entry);
            }
        }
    }

    entries
}

fn try_extract(func: &ItemFn) -> Option<ExportedFn> {
    let no_mangle = has_attr(&func.attrs, "no_mangle");
    let synstream_export = has_attr(&func.attrs, "synstream_export");

    if !no_mangle && !synstream_export {
        return None;
    }

    let fn_name = func.sig.ident.to_string();

    if no_mangle {
        // The function IS the _cm function.
        let cm_name = fn_name.clone();
        let registry_key = cm_name
            .strip_suffix("_cm")
            .map(|s| s.to_string())
            .unwrap_or_else(|| cm_name.clone());

        let cm_params: Vec<CmParam> = func
            .sig
            .inputs
            .iter()
            .filter_map(|arg| {
                let name = extract_param_name(arg)?;
                let ty = extract_param_type(arg)?;
                Some(CmParam {
                    name,
                    kind: classify_cm_param(ty),
                })
            })
            .collect();

        let cm_ret = classify_cm_return(&func.sig.output);

        return Some(ExportedFn {
            cm_name,
            registry_key,
            cm_params,
            cm_ret,
        });
    }

    // synstream_export: infer `_cm` signature from original
    if synstream_export {
        let cm_name = format!("{}_cm", fn_name);
        let registry_key = fn_name.clone();
        let variadic = has_variadic_export(&func.attrs);

        let mut cm_params: Vec<CmParam> = func
            .sig
            .inputs
            .iter()
            .filter_map(|arg| {
                let name = extract_param_name(arg)?;
                let ty = extract_param_type(arg)?;
                Some(CmParam {
                    name,
                    kind: infer_cm_param_kind(ty),
                })
            })
            .collect();

        // Reclassify last param as SliceCmTypes when variadic
        if variadic {
            if let Some(last) = cm_params.last_mut() {
                last.kind = CmParamKind::SliceCmTypes;
            }
        }

        let cm_ret = infer_cm_return(&func.sig.output);

        return Some(ExportedFn {
            cm_name,
            registry_key,
            cm_params,
            cm_ret,
        });
    }

    None
}

// ---------------------------------------------------------------------------
// Code generation helpers
// ---------------------------------------------------------------------------

/// Build the type string used in `cache_sym!` for the function pointer.
/// e.g. `fn(&CmTypes, &CmTypes) -> CmTypes`
fn build_sym_type(entry: &ExportedFn) -> String {
    let mut param_types: Vec<String> = Vec::new();

    for (i, p) in entry.cm_params.iter().enumerate() {
        let is_last = i == entry.cm_params.len() - 1;
        let ty = match &p.kind {
            CmParamKind::CmTypesRef => "&CmTypes".to_string(),
            CmParamKind::Primitive(pk) => pk.rust_type().to_string(),
            CmParamKind::StrRef => "&str".to_string(),
            CmParamKind::OwnedString => "String".to_string(),
            CmParamKind::VecCmTypes => "&Vec<CmTypes>".to_string(),
            CmParamKind::SliceCmTypes => "&[CmTypes]".to_string(),
        };
        param_types.push(ty);
    }

    let ret_ty = match &entry.cm_ret {
        CmRet::Void => String::new(), // no return in the actual _cm symbol
        CmRet::CmTypes => " -> CmTypes".to_string(),
        CmRet::Primitive(pk) => format!(" -> {}", pk.rust_type()),
        CmRet::OwnedString => " -> String".to_string(),
    };

    format!("fn({}){}", param_types.join(", "), ret_ty)
}

/// Build the static symbol name: upper-snake of `cm_name`.
fn sym_static_name(cm_name: &str) -> String {
    format!("{}_SYM", cm_name.to_uppercase())
}

/// Build the wrapper function name.
fn wrap_fn_name(cm_name: &str) -> String {
    format!("{}_wrap", cm_name)
}

// ---------------------------------------------------------------------------
// Rendering wrappers.rs
// ---------------------------------------------------------------------------

fn render_wrappers(entries: &[ExportedFn]) -> String {
    let mut out = String::new();

    out.push_str("use libloading::{Library, Symbol};\n");
    out.push_str("use once_cell::sync::Lazy;\n");
    out.push_str("use synstream_types::*;\n");
    out.push('\n');
    out.push_str("static DYN_LIB: Lazy<Library> = Lazy::new(|| {\n");
    out.push_str(
        "    let path = std::env::var(\"PLUGIN_LIB\").expect(\"PLUGIN_LIB must be set to your .so/.dll\");\n",
    );
    out.push_str(
        "    unsafe { Library::new(path).expect(\"Failed to open plugin library\") }\n",
    );
    out.push_str("});\n\n");
    out.push_str("pub fn init_wrappers() {\n");
    out.push_str("    Lazy::force(&DYN_LIB);\n");
    out.push_str("}\n\n");
    out.push_str("macro_rules! cache_sym {\n");
    out.push_str(
        "    ($vis:vis static $sym:ident : $typ:ty = $name:expr;) => {\n",
    );
    out.push_str(
        "        $vis static $sym: Lazy<$typ> = Lazy::new(|| {\n",
    );
    out.push_str("            let lib = &*DYN_LIB;\n");
    out.push_str(
        "            let sym: Symbol<$typ> =\n",
    );
    out.push_str(
        "                unsafe { lib.get($name) }\n",
    );
    out.push_str(
        "                    .unwrap_or_else(|e| panic!(\"couldn't load symbol {:?}: {}\", $name, e));\n",
    );
    out.push_str("            *sym\n");
    out.push_str("        });\n");
    out.push_str("    };\n");
    out.push_str("}\n\n");

    for entry in entries {
        out.push_str(&render_entry_wrapper(entry));
        out.push('\n');
    }

    out
}

fn render_entry_wrapper(entry: &ExportedFn) -> String {
    let sym_name = sym_static_name(&entry.cm_name);
    let sym_type = build_sym_type(entry);
    let sym_bytes = format!("b\"{}\"", entry.cm_name);
    let wrap_name = wrap_fn_name(&entry.cm_name);

    let mut out = String::new();

    // cache_sym! declaration
    out.push_str(&format!(
        "cache_sym! {{\n    pub static {sym_name}: {sym_type} = {sym_bytes};\n}}\n"
    ));

    // _wrap function
    out.push_str(&format!(
        "pub fn {wrap_name}(args: &[CmTypes]) -> CmTypes {{\n"
    ));

    // Determine which params are "variadic" (VecCmTypes or SliceCmTypes)
    let variadic_idx = entry.cm_params.iter().position(|p| {
        matches!(p.kind, CmParamKind::VecCmTypes | CmParamKind::SliceCmTypes)
    });

    // Emit extraction for each non-variadic param
    for (i, param) in entry.cm_params.iter().enumerate() {
        if matches!(param.kind, CmParamKind::VecCmTypes | CmParamKind::SliceCmTypes) {
            break; // variadic handled below
        }
        let name = &param.name;
        let fn_name_str = &entry.cm_name;
        match &param.kind {
            CmParamKind::CmTypesRef => {
                // Passed as &args[i] — no extraction needed here; handled in call
            }
            CmParamKind::Primitive(pk) => {
                let variant = pk.variant_name();
                out.push_str(&format!(
                    "    let {name} = match args[{i}] {{ CmTypes::{variant}(x) => x, _ => panic!(\"{fn_name_str}: expected {variant} for {name}\") }};\n"
                ));
            }
            CmParamKind::StrRef => {
                // Need a String temp then .as_str()
                out.push_str(&format!(
                    "    let {name}_s = match &args[{i}] {{ CmTypes::String(x) => x.to_string(), _ => panic!(\"{fn_name_str}: expected String for {name}\") }};\n"
                ));
                out.push_str(&format!(
                    "    let {name} = {name}_s.as_str();\n"
                ));
            }
            CmParamKind::OwnedString => {
                out.push_str(&format!(
                    "    let {name} = match &args[{i}] {{ CmTypes::String(x) => x.to_string(), _ => panic!(\"{fn_name_str}: expected String for {name}\") }};\n"
                ));
            }
            CmParamKind::VecCmTypes | CmParamKind::SliceCmTypes => unreachable!(),
        }
    }

    // Handle variadic last param
    if let Some(vi) = variadic_idx {
        let name = &entry.cm_params[vi].name;
        match &entry.cm_params[vi].kind {
            CmParamKind::VecCmTypes => {
                out.push_str(&format!(
                    "    let {name}: Vec<CmTypes> = args[{vi}..].iter().cloned().collect();\n"
                ));
            }
            CmParamKind::SliceCmTypes => {
                // &[CmTypes] — no local variable needed; passed as &args[vi..] in the call
            }
            _ => unreachable!(),
        }
    }

    // Build the call
    let sym_call = build_sym_call(entry, variadic_idx);
    let final_ret = match &entry.cm_ret {
        CmRet::Void => {
            // Symbol returns (), wrapper returns CmTypes::None
            format!("    {sym_call};\n    CmTypes::None\n")
        }
        CmRet::CmTypes => {
            // Symbol returns CmTypes — return it directly
            format!("    {sym_call}\n")
        }
        CmRet::Primitive(pk) => {
            let variant = pk.variant_name();
            format!("    CmTypes::{variant}({sym_call})\n")
        }
        CmRet::OwnedString => {
            format!("    let __result = {sym_call};\n    CmTypes::String(std::sync::Arc::from(__result.as_str()))\n")
        }
    };

    out.push_str(&final_ret);
    out.push_str("}\n");

    out
}

fn build_sym_call(entry: &ExportedFn, variadic_idx: Option<usize>) -> String {
    let sym_name = sym_static_name(&entry.cm_name);

    let args: Vec<String> = entry
        .cm_params
        .iter()
        .enumerate()
        .map(|(i, p)| match &p.kind {
            CmParamKind::CmTypesRef => format!("&args[{}]", i),
            CmParamKind::Primitive(_) => p.name.clone(),
            CmParamKind::StrRef => p.name.clone(),
            CmParamKind::OwnedString => p.name.clone(),
            CmParamKind::VecCmTypes => format!("&{}", p.name),
            CmParamKind::SliceCmTypes => format!("&args[{}..]", i),
        })
        .collect();

    // If variadic, adjust: the variadic param is a collected Vec, we pass &name.
    let _ = variadic_idx; // already handled in args above

    format!("{}({})", sym_name, args.join(", "))
}

// ---------------------------------------------------------------------------
// Rendering func_reg.rs
// ---------------------------------------------------------------------------

fn render_registry(entries: &[ExportedFn]) -> String {
    let mut out = String::new();
    out.push_str("use crate::wrappers::*;\n");
    out.push_str("use synstream_types::*;\n\n");
    out.push_str("pub fn get_func(func_name: &str) -> Option<CmPtr> {\n");
    out.push_str("    match func_name {\n");

    for entry in entries {
        let key = &entry.registry_key;
        let wrap_fn = wrap_fn_name(&entry.cm_name);
        out.push_str(&format!(
            "        \"{key}\" => Some({wrap_fn}),\n"
        ));
    }

    out.push_str("        _ => {\n");
    out.push_str(
        "            println!(\"Function {} not found in registry\", func_name);\n",
    );
    out.push_str(
        "            panic!(\"Function not found: {}\", func_name);\n",
    );
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prim_kind_usize() {
        let kind = prim_kind_from_str("usize");
        assert!(matches!(kind, Some(PrimKind::Usize)));
    }

    #[test]
    fn test_classify_no_mangle_cm() {
        let src = r#"
            #[no_mangle]
            pub fn generate_vector_cm(n: usize) -> CmTypes { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        assert_eq!(e.cm_name, "generate_vector_cm");
        assert_eq!(e.registry_key, "generate_vector");
        assert_eq!(e.cm_params.len(), 1);
        assert!(matches!(e.cm_params[0].kind, CmParamKind::Primitive(PrimKind::Usize)));
        assert!(matches!(e.cm_ret, CmRet::CmTypes));
    }

    #[test]
    fn test_classify_synstream_export() {
        let src = r#"
            #[synstream_export]
            pub fn compute_fft(fft_planner: &SomePlanner, buffer: &mut SomeBuf) { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        assert_eq!(e.cm_name, "compute_fft_cm");
        assert_eq!(e.registry_key, "compute_fft");
        // Both non-primitive refs → CmTypesRef
        assert!(matches!(e.cm_params[0].kind, CmParamKind::CmTypesRef));
        assert!(matches!(e.cm_params[1].kind, CmParamKind::CmTypesRef));
        // void return
        assert!(matches!(e.cm_ret, CmRet::CmTypes));
    }

    #[test]
    fn test_str_param() {
        let src = r#"
            #[no_mangle]
            pub fn get_out_file(env_var: &str, out_file: &str) -> String { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        let e = &entries[0];
        assert_eq!(e.cm_name, "get_out_file");
        assert_eq!(e.registry_key, "get_out_file");
        assert!(matches!(e.cm_params[0].kind, CmParamKind::StrRef));
        assert!(matches!(e.cm_params[1].kind, CmParamKind::StrRef));
        assert!(matches!(e.cm_ret, CmRet::OwnedString));
    }

    #[test]
    fn test_vec_cmtypes_param() {
        let src = r#"
            #[no_mangle]
            pub fn write_to_file(file_path: &str, buffers: &Vec<CmTypes>) { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        let e = &entries[0];
        assert_eq!(e.cm_name, "write_to_file");
        assert!(matches!(e.cm_params[0].kind, CmParamKind::StrRef));
        assert!(matches!(e.cm_params[1].kind, CmParamKind::VecCmTypes));
    }
}
