// In dylib crates all pub functions are exported symbols, so rustc reports
// improper_ctypes_definitions for any that use non-FFI types like &str.
// The actual FFI boundary is the _cm companion generated by #[synstream_export],
// which only uses CmTypes. Suppress the lint for the original Rust-to-Rust functions.
#![allow(improper_ctypes_definitions)]

pub mod functions;
pub mod kernel_perf;
pub mod validation;
pub mod wrap_perf;

use nalgebra::DMatrix;
use num_complex::Complex32;
use rustfft::Fft;
use std::sync::Arc;
use synstream_macro::synstream_export;

/// Generate a vector of complex samples.
#[synstream_export]
pub fn generate_vector(n: usize) -> Vec<Complex32> {
    functions::generate_vector(n)
}

/// Create an FFT planner for the given buffer size.
#[synstream_export]
pub fn fft_planner(buf_size: usize) -> Arc<dyn Fft<f32>> {
    functions::fft_planner(buf_size)
}

/// Run an in-place FFT on `buffer` using the provided planner.
#[allow(clippy::ptr_arg)] // synstream_export macro requires &mut Vec, not &mut [_]
#[synstream_export]
pub fn compute_fft(fft_planner: &Arc<dyn Fft<f32>>, buffer: &mut Vec<Complex32>) {
    functions::compute_fft(fft_planner.clone(), buffer)
}

/// Convert a flat complex vector into a square matrix.
#[synstream_export]
pub fn vec_to_mat(vector: &Vec<Complex32>) -> DMatrix<Complex32> {
    functions::vec_to_mat(vector)
}

/// Multiply two complex matrices.
#[synstream_export]
pub fn mat_mul(a: &DMatrix<Complex32>, b: &DMatrix<Complex32>) -> DMatrix<Complex32> {
    functions::mat_mul(a, b)
}

/// Return the path of the output file, creating it if necessary.
#[synstream_export]
pub fn get_out_file(env_var: &str, out_file: &str) -> String {
    let curr_dir = std::env::var(env_var).unwrap_or_else(|_| {
        panic!(
            "Environment variable '{}' not found or could not be read",
            env_var
        )
    });
    let out_file_path = format!("{}/{}", curr_dir, out_file);
    // Create file if it doesn't exist
    std::fs::File::create(&out_file_path)
        .unwrap_or_else(|_| panic!("Failed to create or open file: {}", out_file_path));
    out_file_path
}

/// Append the contents of each matrix in `buffers` to the file at `file_path`.
#[synstream_export(variadic)]
pub fn write_to_file(file_path: &str, buffers: Vec<DMatrix<Complex32>>) {
    use std::fs::OpenOptions;
    use std::io::Write;

    let mut file = OpenOptions::new()
        .create(false)
        .append(true)
        .open(file_path)
        .expect("Failed to open or create output file");

    for (idx, matrix) in buffers.iter().enumerate() {
        writeln!(file, "Buffer-{}:", idx).expect("Failed to write buffer header");
        write!(file, "{{").expect("Failed to write opening brace");
        for (i, elem) in matrix.iter().enumerate() {
            if i > 0 {
                write!(file, ", ").expect("Failed to write separator");
            }
            write!(file, "{}+{}i", elem.re, elem.im).expect("Failed to write element");
        }
        writeln!(file, "}}").expect("Failed to write closing brace");
    }
}
