#!/usr/bin/env python3
"""UDP IQ frame sender for the radar pipeline (stdlib only).

Streams a scene generated by data/make_scene.py as one UDP packet per chirp,
paced at the scene's frame (CPI) interval. Start the Tomii receiver first,
then this sender (receiver-first startup order).

Packet layout (little-endian), mirroring the mimo-bench 64-byte header:

    offset  0: u32 frame_id     (CPI index, monotonically increasing)
    offset  4: u32 chirp_id     (0 .. n_chirps-1 within the frame)
    offset  8: u32 channel_id   (reserved, 0 -- future multi-channel)
    offset 12: u32 n_samples    (complex samples in payload)
    offset 16: 48 zero bytes    (pad to 64-byte data offset)
    offset 64: n_samples * (i16 I, i16 Q) little-endian

Packet size for the default 1024-sample chirp: 64 + 4096 = 4160 bytes
(fragments on a 1500-MTU path; fine on loopback / jumbo-frame LANs).
"""

import argparse
import json
import socket
import struct
import sys
import time
from pathlib import Path

HEADER = struct.Struct("<4I48x")
DATA_OFFSET = 64


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--scene",
        type=Path,
        default=Path(__file__).resolve().parent / "data" / "out" / "scene.json",
        help="scene.json produced by data/make_scene.py",
    )
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=8100)
    p.add_argument(
        "--frames",
        type=int,
        default=None,
        help="frames to send (default: frames in the scene; more loops the capture "
        "with fresh frame_ids)",
    )
    p.add_argument(
        "--frame-period",
        type=float,
        default=None,
        help="seconds between frame starts (default: scene frame_interval_s)",
    )
    p.add_argument(
        "--chirp-gap-us",
        type=float,
        default=None,
        help="spacing between chirp packets within a frame [us] "
        "(default: the scene's chirp_interval_s, i.e. realistic front-end "
        "pacing; 0 blasts the whole frame as one burst)",
    )
    p.add_argument(
        "--start-delay",
        type=float,
        default=0.0,
        help="seconds to wait before the first packet (receiver warm-up)",
    )
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args(argv)

    scene = json.loads(args.scene.read_text())
    radar = scene["radar"]
    n_samples = radar["n_samples"]
    n_chirps = radar["n_chirps"]
    file_frames = radar["n_frames"]
    frame_period = args.frame_period or radar["frame_interval_s"]
    total_frames = args.frames if args.frames is not None else file_frames

    payload_len = 4 * n_samples
    frame_len = n_chirps * payload_len
    iq = (args.scene.parent / scene["iq_file"]).read_bytes()
    if len(iq) != file_frames * frame_len:
        sys.exit(
            f"IQ file size {len(iq)} != expected {file_frames * frame_len} "
            f"({file_frames} frames x {n_chirps} chirps x {payload_len} B)"
        )
    iq = memoryview(iq)

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    dest = (args.host, args.port)
    if not args.quiet:
        print(
            f"sending {total_frames} frames ({n_chirps} pkts x {DATA_OFFSET + payload_len} B) "
            f"to {dest[0]}:{dest[1]} every {frame_period * 1e3:.2f} ms"
        )

    if args.start_delay:
        time.sleep(args.start_delay)

    # Default to the scene's physical chirp interval so chirps stream across the
    # CPI like a real front-end, instead of one instantaneous burst per frame.
    # A burst can overrun the receiver's socket buffer (kernel-capped at
    # net.core.rmem_max), dropping chirps and stalling that frame's slot.
    if args.chirp_gap_us is None:
        chirp_gap = radar.get("chirp_interval_s", 0.0)
    else:
        chirp_gap = args.chirp_gap_us * 1e-6

    def _spin_until(deadline: float) -> None:
        while True:
            now = time.perf_counter()
            if now >= deadline:
                return
            if deadline - now > 1e-3:
                time.sleep(deadline - now - 1e-3)  # coarse sleep, then busy-wait

    sent_packets = 0
    t0 = time.perf_counter()
    for frame_id in range(total_frames):
        frame_start = t0 + frame_id * frame_period
        _spin_until(frame_start)

        base = (frame_id % file_frames) * frame_len
        for chirp_id in range(n_chirps):
            if chirp_gap:
                _spin_until(frame_start + chirp_id * chirp_gap)
            header = HEADER.pack(frame_id, chirp_id, 0, n_samples)
            off = base + chirp_id * payload_len
            sock.sendto(header + iq[off : off + payload_len], dest)
            sent_packets += 1

    elapsed = time.perf_counter() - t0
    sock.close()
    if not args.quiet:
        period = elapsed / (total_frames - 1) if total_frames > 1 else elapsed
        print(
            f"sent {sent_packets} packets / {total_frames} frames in {elapsed:.3f} s "
            f"(mean frame period {period * 1e3:.2f} ms)"
        )


if __name__ == "__main__":
    main()
