"""Arm 1: random search over the generated knob space.

The search space is generated by `tomii.knob_space` from the runtime knob
catalog + graph.json (see workloads.Workload.knob_space) — no hand-written
option lists.  Uniform sampling per knob over the materialised domains.
Graph knobs may produce verifier-rejected trials; those are logged as
rejections, which is the intended behaviour of a verifier-gated search.
"""

from __future__ import annotations

import argparse
import random
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from harness import (  # noqa: E402
    TrialRecord,
    add_common_args,
    establish_baseline,
    log_trial,
    run_trial,
    setup_arm,
    write_run_meta,
)

from tomii import knobs as tomii_knobs  # noqa: E402


def main() -> None:
    p = argparse.ArgumentParser(description="random search over the knob space")
    add_common_args(p)
    args = p.parse_args()

    t_start = time.monotonic()
    rng = random.Random(args.seed)
    workload, space, results_dir = setup_arm(args)
    log_file = results_dir / "random_trials.jsonl"
    print(
        f"[random] workload={workload.name} knob space v{space['version']}: "
        f"{len(space['knobs'])} knobs, seed={args.seed}",
        flush=True,
    )

    baseline = establish_baseline(
        frames=args.frames,
        warmup=args.warmup,
        results_dir=results_dir,
        workload=workload,
    )
    best_ms = float("inf")

    for i in range(args.iterations):
        knobs = tomii_knobs.sample(space, rng)
        result = run_trial(workload, knobs, args, space)
        record = TrialRecord(
            iteration=i, knobs=knobs, result=result, arm="random",
            extra={"seed": args.seed},
        )
        log_trial(record, log_file)

        if result.verifier_ok and result.ms_per_frame is not None:
            if result.ms_per_frame < best_ms:
                best_ms = result.ms_per_frame
                print(f"[random {i}] new best: {best_ms:.4f} ms/frame", flush=True)
        else:
            print(f"[random {i}] rejected — {result.rejection_reason}", flush=True)

    write_run_meta(
        results_dir, "random", args, space, t_start,
        baseline_ms=baseline, best_ms=best_ms if best_ms < float("inf") else None,
    )
    print(f"\n[random] done: best={best_ms:.4f} ms (baseline {baseline:.4f})")


if __name__ == "__main__":
    main()
