// In dylib crates all pub functions are exported symbols, so rustc reports
// improper_ctypes_definitions for any that use non-FFI types like &str.
// The actual FFI boundary is the _cm companion generated by #[tomii_export],
// which only uses CmTypes. Suppress the lint for the original Rust-to-Rust functions.
#![allow(improper_ctypes_definitions)]

use tomii_macro::tomii_export;

/// Generate a sensor reading slightly above the anomaly threshold.
///
/// With `anomaly_threshold = 5.0` (graph default) this returns 7.5, which the
/// classifier marks as an anomaly.  Raise the threshold to 10.0 in graph.json
/// to see the `smooth` branch fire instead.
#[tomii_export]
pub fn generate_reading(threshold: f64) -> f64 {
    threshold + 2.5
}

/// Classify a reading as anomalous (true) or normal (false).
#[tomii_export]
pub fn classify_reading(reading: f64, threshold: f64) -> bool {
    reading > threshold
}

/// Identity function — used as the condition evaluator for `handle_anomaly`
/// and `smooth`.  The graph condition checks the boolean result of `classify`.
#[tomii_export]
pub fn check_bool(flag: bool) -> bool {
    flag
}

/// Anomaly branch (priority: high): amplify the reading.
/// Only fires when `classify_reading` returns true for this instance.
#[tomii_export]
pub fn amplify_reading(reading: f64) -> f64 {
    reading * 2.0
}

/// Normal branch (priority: low): attenuate the reading.
/// Only fires when `classify_reading` returns false for this instance.
#[tomii_export]
pub fn smooth_reading(reading: f64) -> f64 {
    reading * 0.5
}

/// Compute placeholder statistics for one sensor group.
///
/// Fires once per sensor group (factor = num_sensors = 4) after all
/// `generate` tasks in that group complete via the grouped barrier.
#[tomii_export]
pub fn compute_sensor_stats() -> f64 {
    42.0
}

/// Ordering-only log: fires once after all `classify` tasks complete.
///
/// Scheduled via `$dep` — no classify result is consumed; the dep only
/// establishes a happens-before ordering edge.
#[tomii_export]
pub fn log_stream_event() -> bool {
    println!("[stream-analytics] all {} readings classified", 32);
    true
}

/// Aggregate one sensor group's statistics into a triplet of estimates.
///
/// Fires once per sensor group after compute_stats (1:1 $res) and after
/// all classify tasks in the group complete (grouped $barrier).
#[tomii_export]
pub fn aggregate_results(stats: f64) -> Vec<f64> {
    vec![stats - 0.5, stats, stats + 0.5]
}

/// Write per-sensor summaries to the result file.
///
/// Variadic fan-in: collects all `num_sensors` aggregate results.
/// Each element is a `Vec<f64>` triplet produced by `aggregate_results`.
#[tomii_export(variadic)]
pub fn write_report(file_path: &str, sensor_summaries: Vec<Vec<f64>>) {
    use std::fs::OpenOptions;
    use std::io::Write;

    let mut out = String::new();
    for (sensor_id, estimates) in sensor_summaries.iter().enumerate() {
        let formatted: Vec<String> = estimates.iter().map(|v| format!("{:.2}", v)).collect();
        out.push_str(&format!(
            "Sensor-{}: [{}]\n",
            sensor_id,
            formatted.join(", ")
        ));
    }

    let mut file = OpenOptions::new()
        .create(false)
        .append(true)
        .open(file_path)
        .expect("Failed to open report file");
    file.write_all(out.as_bytes())
        .expect("Failed to write sensor summary");
}

/// Resolve the path of the output file, creating it if absent.
#[tomii_export]
pub fn get_out_file(env_var: &str, out_file: &str) -> String {
    let dir = std::env::var(env_var)
        .unwrap_or_else(|_| panic!("Environment variable '{}' not set", env_var));
    let path = format!("{}/{}", dir, out_file);
    std::fs::File::create(&path)
        .unwrap_or_else(|_| panic!("Failed to create output file: {}", path));
    path
}

/// Post-stream cleanup — runs once after the full graph completes each stream.
#[tomii_export]
pub fn cleanup_state() {
    println!("[stream-analytics] stream cleanup complete");
}
