//! Rust-native wrapper and registry generator for Τομί plugins.
//!
//! Parses a Rust source file (`.rs`) or C header (`.h`/`.hpp`) and produces two generated files:
//!
//! - `wrappers.rs` – `cache_sym!` statics + `_wrap` functions for each exported function.
//! - `func_reg.rs` – `get_func` registry mapping string names → `CmPtr`.
//!
//! Two kinds of source annotations are recognised for Rust files:
//!
//! 1. `#[no_mangle] pub fn` – these are already the `_cm` bridge functions.
//!    The converter reads their actual types directly.
//!
//! 2. `#[tomii_export] pub fn` – these are the original domain functions.
//!    The converter infers the `_cm` signature using the same classification
//!    logic as the proc-macro in `tomii-macro`.
//!
//! For C headers, functions annotated with `// @tomii_export` (and optional
//! attributes) are parsed and wrapped using `libloading` dynamic dispatch.

use std::path::Path;

use syn::{
    parse_str, Attribute, File, FnArg, Item, ItemFn, Pat, PatType, ReturnType, Type, TypePath,
    TypeReference,
};

mod c_header;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Parse `input_path`, then write `wrappers_output` and `registry_output`.
///
/// Dispatches to either the Rust AST path (`syn`) or the C header parser
/// based on the file extension (`.rs` → Rust; `.h`/`.hpp` → C).
///
/// # Errors
///
/// Returns an error if the input cannot be read or parsed, or if writing
/// either output file fails.
pub fn generate_from_file(
    input_path: &Path,
    wrappers_output: &Path,
    registry_output: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let source = std::fs::read_to_string(input_path)
        .map_err(|e| format!("cannot read {}: {}", input_path.display(), e))?;

    let ext = input_path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("");

    let entries: Vec<ExportedFn> = match ext {
        "rs" => {
            let ast: File = parse_str(&source)
                .map_err(|e| format!("cannot parse {}: {}", input_path.display(), e))?;
            collect_entries(&ast)
        }
        "h" | "hpp" => c_header::collect_c_entries(&source),
        other => return Err(format!("unsupported extension: {other}").into()),
    };

    let wrappers_code = render_wrappers(&entries);
    let registry_code = render_registry(&entries);

    std::fs::write(wrappers_output, wrappers_code)
        .map_err(|e| format!("cannot write {}: {}", wrappers_output.display(), e))?;
    std::fs::write(registry_output, registry_code)
        .map_err(|e| format!("cannot write {}: {}", registry_output.display(), e))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Data model
// ---------------------------------------------------------------------------

/// Which language produced this entry.
#[derive(Debug, Clone, Copy, PartialEq)]
enum SourceLang {
    Rust,
    C,
}

/// A single exported function, with the `_cm`-equivalent signature resolved.
#[derive(Debug)]
struct ExportedFn {
    /// The symbol name to load / call.
    /// For Rust `#[no_mangle]`: the `_cm` function name (e.g. `generate_vector_cm`).
    /// For C: the original C function name (e.g. `fft_planner`).
    cm_name: String,
    /// The registry key (e.g. `"generate_vector"` or `"fft_planner"`).
    registry_key: String,
    /// Parameters as they appear in the **`_cm` / C** function signature.
    cm_params: Vec<CmParam>,
    /// Return type of the `_cm` / C function.
    cm_ret: CmRet,
    /// Which backend generated this entry.
    source_lang: SourceLang,
    /// Names of C companion length parameters that are NOT consumed from
    /// `CmTypes` args — they are auto-derived from array metadata in the `_wrap`.
    auto_params: Vec<String>,
    /// True when a `{registry_key}_bulk_cm` symbol was found alongside this entry.
    /// When set, `render_wrappers` emits a `_bulk_cm_wrap` passthrough and
    /// `render_registry` includes this key in `get_bulk_func`.
    has_bulk_cm: bool,
}

/// A parameter as seen in the `_cm` / C function.
#[derive(Debug, Clone)]
struct CmParam {
    name: String,
    kind: CmParamKind,
}

/// How a parameter should be extracted from `args: &[CmTypes]`.
#[derive(Debug, Clone)]
enum CmParamKind {
    /// `&CmTypes` — pass `&args[i]` directly.
    CmTypesRef,
    /// A primitive whose `CmTypes` variant is known.
    Primitive(PrimKind),
    /// `&str` — extract from `CmTypes::String`.
    StrRef,
    /// Owned `String` — extract from `CmTypes::String`.
    OwnedString,
    /// `&Vec<CmTypes>` — collect `args[i..]`.
    VecCmTypes,
    /// `&[CmTypes]` — pass `&args[i..]` directly (generated by `variadic` macro).
    SliceCmTypes,
    /// C `void*` opaque handle — stored in `CmTypes::Any(OpaqueHandle)`.
    OpaquePtr,
    /// C const array pointer (e.g. `complex_f32*`, `float*`) — stored in `CmTypes::Any(Vec<T>)`.
    /// `len_param` is the companion `size_t` parameter name that is auto-derived.
    ArrayPtr {
        c_element_type: String,
        len_param: String,
    },
    /// C mutable array pointer — buffer passed to C for in-place modification.
    MutArrayPtr {
        c_element_type: String,
        len_param: String,
    },
}

#[derive(Debug, Clone)]
enum PrimKind {
    Bool,
    I8,
    I16,
    I32,
    I64,
    I128,
    U8,
    U16,
    U32,
    U64,
    U128,
    F32,
    F64,
    Usize,
    Isize,
    Char,
}

impl PrimKind {
    fn variant_name(&self) -> &'static str {
        match self {
            PrimKind::Bool => "Bool",
            PrimKind::I8 => "I8",
            PrimKind::I16 => "I16",
            PrimKind::I32 => "I32",
            PrimKind::I64 => "I64",
            PrimKind::I128 => "I128",
            PrimKind::U8 => "U8",
            PrimKind::U16 => "U16",
            PrimKind::U32 => "U32",
            PrimKind::U64 => "U64",
            PrimKind::U128 => "U128",
            PrimKind::F32 => "F32",
            PrimKind::F64 => "F64",
            PrimKind::Usize => "Usize",
            PrimKind::Isize => "Isize",
            PrimKind::Char => "Char",
        }
    }

    fn rust_type(&self) -> &'static str {
        match self {
            PrimKind::Bool => "bool",
            PrimKind::I8 => "i8",
            PrimKind::I16 => "i16",
            PrimKind::I32 => "i32",
            PrimKind::I64 => "i64",
            PrimKind::I128 => "i128",
            PrimKind::U8 => "u8",
            PrimKind::U16 => "u16",
            PrimKind::U32 => "u32",
            PrimKind::U64 => "u64",
            PrimKind::U128 => "u128",
            PrimKind::F32 => "f32",
            PrimKind::F64 => "f64",
            PrimKind::Usize => "usize",
            PrimKind::Isize => "isize",
            PrimKind::Char => "char",
        }
    }
}

/// Return kind of the `_cm` / C function.
#[derive(Debug, Clone)]
enum CmRet {
    /// The function is void; `_wrap` returns `CmTypes::None`.
    Void,
    /// Returns `CmTypes` directly (Rust path only).
    CmTypes,
    /// Returns a primitive (needs wrapping into a `CmTypes::Variant`).
    Primitive(PrimKind),
    /// Returns `String` (needs `CmTypes::String(Arc::from(...))`).
    OwnedString,
    /// C returns `void*` — wrap in `CmTypes::from_any(OpaqueHandle(ptr))`.
    OpaquePtr,
    /// C returns a heap-allocated array — copy to `Vec<T>`, optionally free, wrap in `CmTypes::from_any`.
    AllocatedArray {
        c_element_type: String,
        len_from_param: String,
        free_fn: Option<String>,
    },
    /// C returns a malloc'd `char*` — copy to `String`, optionally free.
    AllocatedString { free_fn: Option<String> },
}

// ---------------------------------------------------------------------------
// Type classification helpers
// ---------------------------------------------------------------------------

fn prim_kind_from_str(name: &str) -> Option<PrimKind> {
    match name {
        "bool" => Some(PrimKind::Bool),
        "i8" => Some(PrimKind::I8),
        "i16" => Some(PrimKind::I16),
        "i32" => Some(PrimKind::I32),
        "i64" => Some(PrimKind::I64),
        "i128" => Some(PrimKind::I128),
        "u8" => Some(PrimKind::U8),
        "u16" => Some(PrimKind::U16),
        "u32" => Some(PrimKind::U32),
        "u64" => Some(PrimKind::U64),
        "u128" => Some(PrimKind::U128),
        "f32" => Some(PrimKind::F32),
        "f64" => Some(PrimKind::F64),
        "usize" => Some(PrimKind::Usize),
        "isize" => Some(PrimKind::Isize),
        "char" => Some(PrimKind::Char),
        _ => None,
    }
}

fn is_primitive_ident(name: &str) -> bool {
    prim_kind_from_str(name).is_some()
}

fn type_path_ident(ty: &Type) -> Option<String> {
    if let Type::Path(TypePath { qself: None, path }) = ty {
        if path.segments.len() == 1 {
            return Some(path.segments[0].ident.to_string());
        }
        // Multi-segment: return last segment
        return path.segments.last().map(|s| s.ident.to_string());
    }
    None
}

fn ref_is_str(r: &TypeReference) -> bool {
    if let Type::Path(TypePath { qself: None, path }) = r.elem.as_ref() {
        path.segments.len() == 1 && path.segments[0].ident == "str"
    } else {
        false
    }
}

fn ref_is_cm_types(r: &TypeReference) -> bool {
    type_path_ident(r.elem.as_ref())
        .map(|n| n == "CmTypes")
        .unwrap_or(false)
}

/// Check if `&[CmTypes]` (generated by `variadic` macro attribute).
fn ref_is_slice_cm_types(r: &TypeReference) -> bool {
    if let Type::Slice(slice) = r.elem.as_ref() {
        type_path_ident(&slice.elem)
            .map(|n| n == "CmTypes")
            .unwrap_or(false)
    } else {
        false
    }
}

/// Check if `&Vec<CmTypes>` (last variadic parameter).
fn ref_is_vec_cm_types(r: &TypeReference) -> bool {
    if let Type::Path(TypePath { qself: None, path }) = r.elem.as_ref() {
        if path.segments.len() == 1 && path.segments[0].ident == "Vec" {
            if let syn::PathArguments::AngleBracketed(ab) = &path.segments[0].arguments {
                if ab.args.len() == 1 {
                    if let syn::GenericArgument::Type(inner) = &ab.args[0] {
                        return type_path_ident(inner)
                            .map(|n| n == "CmTypes")
                            .unwrap_or(false);
                    }
                }
            }
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Classifying `_cm` parameters (from actual `#[no_mangle]` signature)
// ---------------------------------------------------------------------------

fn classify_cm_param(ty: &Type) -> CmParamKind {
    match ty {
        Type::Reference(r) => {
            if ref_is_str(r) {
                CmParamKind::StrRef
            } else if ref_is_cm_types(r) {
                CmParamKind::CmTypesRef
            } else if ref_is_slice_cm_types(r) {
                CmParamKind::SliceCmTypes
            } else if ref_is_vec_cm_types(r) {
                CmParamKind::VecCmTypes
            } else {
                // Unknown ref — treat as CmTypesRef (safe fallback)
                CmParamKind::CmTypesRef
            }
        }
        Type::Path(_) => {
            let name = type_path_ident(ty).unwrap_or_default();
            if let Some(pk) = prim_kind_from_str(&name) {
                CmParamKind::Primitive(pk)
            } else if name == "String" {
                CmParamKind::OwnedString
            } else if name == "CmTypes" {
                // Owned CmTypes — pass directly
                CmParamKind::CmTypesRef
            } else {
                CmParamKind::CmTypesRef
            }
        }
        _ => CmParamKind::CmTypesRef,
    }
}

// ---------------------------------------------------------------------------
// Classifying return type of `_cm` functions
// ---------------------------------------------------------------------------

fn classify_cm_return(ret: &ReturnType) -> CmRet {
    match ret {
        ReturnType::Default => CmRet::Void, // void → _wrap returns CmTypes::None
        ReturnType::Type(_, ty) => {
            let name = type_path_ident(ty).unwrap_or_default();
            match name.as_str() {
                "CmTypes" => CmRet::CmTypes,
                "String" => CmRet::OwnedString,
                other => {
                    if let Some(pk) = prim_kind_from_str(other) {
                        CmRet::Primitive(pk)
                    } else {
                        // Assume the function returns CmTypes (common case for _cm functions)
                        CmRet::CmTypes
                    }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Inferring `_cm` parameter types from `#[tomii_export]` original signature
// ---------------------------------------------------------------------------

/// Given a parameter type from the *original* (non-`_cm`) function, infer
/// what the `_cm` counterpart parameter type and extraction kind would be.
fn infer_cm_param_kind(ty: &Type) -> CmParamKind {
    match ty {
        Type::Reference(r) => {
            if ref_is_str(r) {
                // `&str` → keep as `&str` in `_cm`, extract from String
                CmParamKind::StrRef
            } else {
                // `&T` or `&mut T` for non-primitive → `&CmTypes`
                CmParamKind::CmTypesRef
            }
        }
        Type::Path(_) => {
            let name = type_path_ident(ty).unwrap_or_default();
            if is_primitive_ident(&name) || name == "String" {
                // Primitive or String — passthrough in `_cm`
                if name == "String" {
                    CmParamKind::OwnedString
                } else if let Some(pk) = prim_kind_from_str(&name) {
                    CmParamKind::Primitive(pk)
                } else {
                    CmParamKind::CmTypesRef
                }
            } else {
                // Owned non-primitive → `&CmTypes`
                CmParamKind::CmTypesRef
            }
        }
        _ => CmParamKind::CmTypesRef,
    }
}

/// Infer return kind for `_cm` from the original function return type.
fn infer_cm_return(ret: &ReturnType) -> CmRet {
    // The proc-macro ALWAYS generates a `_cm` that returns `-> CmTypes`.
    // So regardless of whether the original function is void, returns a primitive,
    // returns String, or returns an opaque type, the companion `_cm` symbol always
    // has `-> CmTypes` in its signature.
    match ret {
        ReturnType::Default => CmRet::CmTypes, // void original → _cm returns CmTypes::None
        ReturnType::Type(_, ty) => {
            let name = type_path_ident(ty).unwrap_or_default();
            match name.as_str() {
                "CmTypes" => CmRet::CmTypes,
                // All other return types (String, primitives, opaque) → the proc-macro
                // wraps them into CmTypes, so the _cm symbol still returns CmTypes.
                _ => CmRet::CmTypes,
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Attribute helpers
// ---------------------------------------------------------------------------

fn has_attr(attrs: &[Attribute], name: &str) -> bool {
    attrs.iter().any(|a| {
        let path = a.path();
        path.segments
            .last()
            .map(|s| s.ident == name)
            .unwrap_or(false)
    })
}

/// Returns true if `#[tomii_export(variadic)]` is present.
fn has_variadic_export(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        let is_export = a
            .path()
            .segments
            .last()
            .map(|s| s.ident == "tomii_export")
            .unwrap_or(false);
        if !is_export {
            return false;
        }
        // Check if the attribute tokens contain "variadic"
        matches!(a.meta, syn::Meta::List(_)) && {
            if let syn::Meta::List(ref ml) = a.meta {
                ml.tokens.to_string().contains("variadic")
            } else {
                false
            }
        }
    })
}

fn extract_param_name(arg: &FnArg) -> Option<String> {
    if let FnArg::Typed(PatType { pat, .. }) = arg {
        if let Pat::Ident(pi) = pat.as_ref() {
            return Some(pi.ident.to_string());
        }
    }
    None
}

fn extract_param_type(arg: &FnArg) -> Option<&Type> {
    if let FnArg::Typed(PatType { ty, .. }) = arg {
        Some(ty.as_ref())
    } else {
        None
    }
}

// ---------------------------------------------------------------------------
// Collecting entries from the AST
// ---------------------------------------------------------------------------

fn collect_entries(file: &File) -> Vec<ExportedFn> {
    // First pass: collect all no_mangle function names present in the file.
    // This lets us detect `{fn}_bulk_cm` companions emitted by `#[tomii_export(bulk)]`.
    let no_mangle_names: std::collections::HashSet<String> = file
        .items
        .iter()
        .filter_map(|item| {
            if let Item::Fn(func) = item {
                if has_attr(&func.attrs, "no_mangle") {
                    return Some(func.sig.ident.to_string());
                }
            }
            None
        })
        .collect();

    // Also collect keys of functions annotated with `#[tomii_export(bulk)]`
    // so we can mark entries that have a bulk companion even if the companion
    // is generated (not yet present in the source) but will be present at link time.
    let bulk_export_keys: std::collections::HashSet<String> = file
        .items
        .iter()
        .filter_map(|item| {
            if let Item::Fn(func) = item {
                if has_attr(&func.attrs, "tomii_export") && has_bulk_export(&func.attrs) {
                    return Some(func.sig.ident.to_string());
                }
            }
            None
        })
        .collect();

    // Collect the _cm companion names generated for every #[tomii_export] function.
    // A no_mangle symbol named `{fn}_bulk_cm` might actually be the per-cell companion
    // for a function named `{fn}_bulk` (not a bulk companion for `{fn}`).  Excluding
    // names that belong to an existing tomii_export entry prevents that false positive.
    let tomii_export_cm_names: std::collections::HashSet<String> = file
        .items
        .iter()
        .filter_map(|item| {
            if let Item::Fn(func) = item {
                if has_attr(&func.attrs, "tomii_export") {
                    return Some(format!("{}_cm", func.sig.ident));
                }
            }
            None
        })
        .collect();

    let mut entries = Vec::new();

    for item in &file.items {
        if let Item::Fn(func) = item {
            if let Some(mut entry) = try_extract(func) {
                // Probe for a `{registry_key}_bulk_cm` symbol: present as a no_mangle
                // function in the source (and not the per-cell companion for another
                // tomii_export function), OR the function itself has `#[tomii_export(bulk)]`.
                let bulk_cm_sym = format!("{}_bulk_cm", entry.registry_key);
                entry.has_bulk_cm =
                    (no_mangle_names.contains(&bulk_cm_sym)
                        && !tomii_export_cm_names.contains(&bulk_cm_sym))
                        || bulk_export_keys.contains(&entry.registry_key);
                entries.push(entry);
            }
        }
    }

    entries
}

/// Returns true if `#[tomii_export(bulk)]` is present on the function.
fn has_bulk_export(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        let is_export = a
            .path()
            .segments
            .last()
            .map(|s| s.ident == "tomii_export")
            .unwrap_or(false);
        if !is_export {
            return false;
        }
        matches!(a.meta, syn::Meta::List(_)) && {
            if let syn::Meta::List(ref ml) = a.meta {
                ml.tokens.to_string().contains("bulk")
            } else {
                false
            }
        }
    })
}

fn try_extract(func: &ItemFn) -> Option<ExportedFn> {
    let no_mangle = has_attr(&func.attrs, "no_mangle");
    let tomii_export = has_attr(&func.attrs, "tomii_export");

    if !no_mangle && !tomii_export {
        return None;
    }

    let fn_name = func.sig.ident.to_string();

    if no_mangle {
        // The function IS the _cm function.
        let cm_name = fn_name.clone();
        let registry_key = cm_name
            .strip_suffix("_cm")
            .map(|s| s.to_string())
            .unwrap_or_else(|| cm_name.clone());

        let cm_params: Vec<CmParam> = func
            .sig
            .inputs
            .iter()
            .filter_map(|arg| {
                let name = extract_param_name(arg)?;
                let ty = extract_param_type(arg)?;
                Some(CmParam {
                    name,
                    kind: classify_cm_param(ty),
                })
            })
            .collect();

        let cm_ret = classify_cm_return(&func.sig.output);

        return Some(ExportedFn {
            cm_name,
            registry_key,
            cm_params,
            cm_ret,
            source_lang: SourceLang::Rust,
            auto_params: vec![],
            has_bulk_cm: false, // populated by collect_entries after full file scan
        });
    }

    // tomii_export: infer `_cm` signature from original
    if tomii_export {
        let cm_name = format!("{}_cm", fn_name);
        let registry_key = fn_name.clone();
        let variadic = has_variadic_export(&func.attrs);

        let mut cm_params: Vec<CmParam> = func
            .sig
            .inputs
            .iter()
            .filter_map(|arg| {
                let name = extract_param_name(arg)?;
                let ty = extract_param_type(arg)?;
                Some(CmParam {
                    name,
                    kind: infer_cm_param_kind(ty),
                })
            })
            .collect();

        // Reclassify last param as SliceCmTypes when variadic
        if variadic {
            if let Some(last) = cm_params.last_mut() {
                last.kind = CmParamKind::SliceCmTypes;
            }
        }

        let cm_ret = infer_cm_return(&func.sig.output);

        return Some(ExportedFn {
            cm_name,
            registry_key,
            cm_params,
            cm_ret,
            source_lang: SourceLang::Rust,
            auto_params: vec![],
            has_bulk_cm: false, // populated by collect_entries after full file scan
        });
    }

    None
}

// ---------------------------------------------------------------------------
// Code generation helpers
// ---------------------------------------------------------------------------

/// Build the type string used in `cache_sym!` for the function pointer.
///
/// For Rust entries: `fn(&CmTypes, &CmTypes) -> CmTypes`
/// For C entries: `unsafe extern "C" fn(*mut c_void, usize) -> *mut c_void`
fn build_sym_type(entry: &ExportedFn) -> String {
    if entry.source_lang == SourceLang::C {
        return build_c_sym_type(entry);
    }

    let mut param_types: Vec<String> = Vec::new();

    for p in &entry.cm_params {
        let ty = match &p.kind {
            CmParamKind::CmTypesRef => "&CmTypes".to_string(),
            CmParamKind::Primitive(pk) => pk.rust_type().to_string(),
            CmParamKind::StrRef => "&str".to_string(),
            CmParamKind::OwnedString => "String".to_string(),
            CmParamKind::VecCmTypes => "&Vec<CmTypes>".to_string(),
            CmParamKind::SliceCmTypes => "&[CmTypes]".to_string(),
            // These only appear in C entries — handled above
            CmParamKind::OpaquePtr
            | CmParamKind::ArrayPtr { .. }
            | CmParamKind::MutArrayPtr { .. } => unreachable!("C-only kinds in Rust entry"),
        };
        param_types.push(ty);
    }

    let ret_ty = match &entry.cm_ret {
        CmRet::Void => String::new(), // no return in the actual _cm symbol
        CmRet::CmTypes => " -> CmTypes".to_string(),
        CmRet::Primitive(pk) => format!(" -> {}", pk.rust_type()),
        CmRet::OwnedString => " -> String".to_string(),
        // C-only variants
        CmRet::OpaquePtr | CmRet::AllocatedArray { .. } | CmRet::AllocatedString { .. } => {
            unreachable!("C-only return kinds in Rust entry")
        }
    };

    format!("fn({}){}", param_types.join(", "), ret_ty)
}

/// Build the `unsafe extern "C" fn(...)` type string for a C entry.
///
/// For each parameter that has a companion length (ArrayPtr / MutArrayPtr),
/// two slots are emitted: the raw pointer slot AND a `usize` length slot.
/// Auto-derived `size_t` params that are companions are emitted in-place.
fn build_c_sym_type(entry: &ExportedFn) -> String {
    let mut param_types: Vec<String> = Vec::new();

    for p in &entry.cm_params {
        match &p.kind {
            CmParamKind::Primitive(pk) => {
                param_types.push(pk.rust_type().to_string());
            }
            CmParamKind::StrRef => {
                // Pass CString.as_ptr() as *const std::ffi::c_char
                param_types.push("*const std::ffi::c_char".to_string());
            }
            CmParamKind::OpaquePtr => {
                param_types.push("*mut c_void".to_string());
            }
            CmParamKind::ArrayPtr { .. } => {
                // raw const ptr + companion usize length
                param_types.push("*const c_void".to_string());
                param_types.push("usize".to_string());
            }
            CmParamKind::MutArrayPtr { .. } => {
                // raw mut ptr + companion usize length
                param_types.push("*mut c_void".to_string());
                param_types.push("usize".to_string());
            }
            CmParamKind::SliceCmTypes => {
                // variadic: array of opaque ptrs + count
                param_types.push("*const *mut c_void".to_string());
                param_types.push("usize".to_string());
            }
            CmParamKind::CmTypesRef | CmParamKind::OwnedString | CmParamKind::VecCmTypes => {
                unreachable!("Rust-only kinds in C entry");
            }
        }
    }

    // Also emit auto-derived size_t params that appear in the C signature but
    // are NOT in cm_params (they were stripped into auto_params).
    // These are already accounted for by the extra `usize` emitted per ArrayPtr above.

    let ret_ty = match &entry.cm_ret {
        CmRet::Void => String::new(),
        CmRet::Primitive(pk) => format!(" -> {}", pk.rust_type()),
        CmRet::OpaquePtr => " -> *mut c_void".to_string(),
        CmRet::AllocatedArray { .. } => " -> *mut c_void".to_string(),
        CmRet::AllocatedString { .. } => " -> *mut c_void".to_string(),
        CmRet::CmTypes | CmRet::OwnedString => {
            unreachable!("Rust-only return kinds in C entry")
        }
    };

    format!(
        "unsafe extern \"C\" fn({}){}",
        param_types.join(", "),
        ret_ty
    )
}

/// Map a C element type string to its Rust equivalent for `Vec<T>` wrappers.
/// Strips leading `const` before matching.
fn c_elem_rust_type(c_type: &str) -> &'static str {
    let base = c_type.trim_start_matches("const").trim();
    match base {
        "float" => "f32",
        "double" => "f64",
        "int" | "int32_t" => "i32",
        "uint32_t" | "unsigned int" => "u32",
        "int64_t" => "i64",
        "uint64_t" => "u64",
        "size_t" | "usize" => "usize",
        "void" => "[f32; 2]", // void* array treated as complex_f32 (legacy)
        _ => "[f32; 2]",      // custom struct (e.g. complex_f32) has same layout
    }
}

/// Build the static symbol name: upper-snake of `cm_name`.
fn sym_static_name(cm_name: &str) -> String {
    format!("{}_SYM", cm_name.to_uppercase())
}

/// Build the wrapper function name.
fn wrap_fn_name(cm_name: &str) -> String {
    format!("{}_wrap", cm_name)
}

// ---------------------------------------------------------------------------
// Rendering wrappers.rs
// ---------------------------------------------------------------------------

fn render_wrappers(entries: &[ExportedFn]) -> String {
    let mut out = String::new();

    out.push_str("use libloading::{Library, Symbol};\n");
    out.push_str("use std::sync::LazyLock;\n");
    out.push_str("use tomii_types::*;\n");

    // Add C FFI imports if any C entries are present
    if entries.iter().any(|e| e.source_lang == SourceLang::C) {
        out.push_str("use std::ffi::{c_void, CString, CStr};\n");
    }

    out.push('\n');
    out.push_str("static DYN_LIB: LazyLock<Library> = LazyLock::new(|| {\n");
    out.push_str(
        "    let path = std::env::var(\"PLUGIN_LIB\").expect(\"PLUGIN_LIB must be set to your .so/.dll\");\n",
    );
    out.push_str("    unsafe { Library::new(path).expect(\"Failed to open plugin library\") }\n");
    out.push_str("});\n\n");
    out.push_str("pub fn init_wrappers() {\n");
    out.push_str("    LazyLock::force(&DYN_LIB);\n");
    out.push_str("}\n\n");
    out.push_str("macro_rules! cache_sym {\n");
    out.push_str("    ($vis:vis static $sym:ident : $typ:ty = $name:expr;) => {\n");
    out.push_str("        $vis static $sym: LazyLock<$typ> = LazyLock::new(|| {\n");
    out.push_str("            let lib = &*DYN_LIB;\n");
    out.push_str("            let sym: Symbol<$typ> =\n");
    out.push_str("                unsafe { lib.get($name) }\n");
    out.push_str(
        "                    .unwrap_or_else(|e| panic!(\"couldn't load symbol {:?}: {}\", $name, e));\n",
    );
    out.push_str("            *sym\n");
    out.push_str("        });\n");
    out.push_str("    };\n");
    out.push_str("}\n\n");

    // Emit OpaqueHandle newtype if any C entries are present
    if entries.iter().any(|e| e.source_lang == SourceLang::C) {
        out.push_str("#[derive(Debug)]\n");
        out.push_str("pub(crate) struct OpaqueHandle(pub *mut c_void);\n");
        out.push_str("unsafe impl Send for OpaqueHandle {}\n");
        out.push_str("unsafe impl Sync for OpaqueHandle {}\n");
        out.push('\n');
    }

    for entry in entries {
        out.push_str(&render_entry_wrapper(entry));
        out.push('\n');
        // If a _bulk_cm companion exists, emit a trivial passthrough wrapper.
        if entry.has_bulk_cm && entry.source_lang == SourceLang::Rust {
            out.push_str(&render_bulk_entry_wrapper(entry));
            out.push('\n');
        }
    }

    out
}

fn render_entry_wrapper(entry: &ExportedFn) -> String {
    if entry.source_lang == SourceLang::C {
        return render_c_entry_wrapper(entry);
    }

    let sym_name = sym_static_name(&entry.cm_name);
    let sym_type = build_sym_type(entry);
    let sym_bytes = format!("b\"{}\"", entry.cm_name);
    let wrap_name = wrap_fn_name(&entry.cm_name);

    let mut out = String::new();

    // cache_sym! declaration
    out.push_str(&format!(
        "cache_sym! {{\n    pub static {sym_name}: {sym_type} = {sym_bytes};\n}}\n"
    ));

    // _wrap function
    out.push_str(&format!(
        "pub fn {wrap_name}(args: &[CmTypes]) -> CmTypes {{\n"
    ));

    // Determine which params are "variadic" (VecCmTypes or SliceCmTypes)
    let variadic_idx = entry
        .cm_params
        .iter()
        .position(|p| matches!(p.kind, CmParamKind::VecCmTypes | CmParamKind::SliceCmTypes));

    // Emit extraction for each non-variadic param
    for (i, param) in entry.cm_params.iter().enumerate() {
        if matches!(
            param.kind,
            CmParamKind::VecCmTypes | CmParamKind::SliceCmTypes
        ) {
            break; // variadic handled below
        }
        let name = &param.name;
        let fn_name_str = &entry.cm_name;
        match &param.kind {
            CmParamKind::CmTypesRef => {
                // Passed as &args[i] — no extraction needed here; handled in call
            }
            CmParamKind::Primitive(pk) => {
                let variant = pk.variant_name();
                out.push_str(&format!(
                    "    let {name} = match args[{i}] {{ CmTypes::{variant}(x) => x, _ => panic!(\"{fn_name_str}: expected {variant} for {name}\") }};\n"
                ));
            }
            CmParamKind::StrRef => {
                // Need a String temp then .as_str()
                out.push_str(&format!(
                    "    let {name}_s = match &args[{i}] {{ CmTypes::String(x) => x.to_string(), _ => panic!(\"{fn_name_str}: expected String for {name}\") }};\n"
                ));
                out.push_str(&format!("    let {name} = {name}_s.as_str();\n"));
            }
            CmParamKind::OwnedString => {
                out.push_str(&format!(
                    "    let {name} = match &args[{i}] {{ CmTypes::String(x) => x.to_string(), _ => panic!(\"{fn_name_str}: expected String for {name}\") }};\n"
                ));
            }
            CmParamKind::VecCmTypes | CmParamKind::SliceCmTypes => unreachable!(),
            CmParamKind::OpaquePtr
            | CmParamKind::ArrayPtr { .. }
            | CmParamKind::MutArrayPtr { .. } => unreachable!("C-only kinds in Rust entry"),
        }
    }

    // Handle variadic last param
    if let Some(vi) = variadic_idx {
        let name = &entry.cm_params[vi].name;
        match &entry.cm_params[vi].kind {
            CmParamKind::VecCmTypes => {
                out.push_str(&format!(
                    "    let {name}: Vec<CmTypes> = args[{vi}..].iter().cloned().collect();\n"
                ));
            }
            CmParamKind::SliceCmTypes => {
                // &[CmTypes] — no local variable needed; passed as &args[vi..] in the call
            }
            _ => unreachable!(),
        }
    }

    // Build the call
    let sym_call = build_rust_sym_call(entry, variadic_idx);
    let final_ret = match &entry.cm_ret {
        CmRet::Void => {
            // Symbol returns (), wrapper returns CmTypes::None
            format!("    {sym_call};\n    CmTypes::None\n")
        }
        CmRet::CmTypes => {
            // Symbol returns CmTypes — return it directly
            format!("    {sym_call}\n")
        }
        CmRet::Primitive(pk) => {
            let variant = pk.variant_name();
            format!("    CmTypes::{variant}({sym_call})\n")
        }
        CmRet::OwnedString => {
            format!("    let __result = {sym_call};\n    CmTypes::String(std::sync::Arc::from(__result.as_str()))\n")
        }
        CmRet::OpaquePtr | CmRet::AllocatedArray { .. } | CmRet::AllocatedString { .. } => {
            unreachable!("C-only return kinds in Rust entry")
        }
    };

    out.push_str(&final_ret);
    out.push_str("}\n");

    out
}

/// Emit a `cache_sym!` + trivial `_bulk_cm_wrap` passthrough for Rust entries that have
/// a `{registry_key}_bulk_cm` companion symbol.
///
/// The passthrough simply forwards `(start, end, args)` to the cached symbol — no argument
/// extraction is needed because the bulk kernel owns its own iteration and arg interpretation.
fn render_bulk_entry_wrapper(entry: &ExportedFn) -> String {
    let bulk_cm_name = format!("{}_bulk_cm", entry.registry_key);
    let sym_name = format!("{}_SYM", bulk_cm_name.to_uppercase());
    let sym_bytes = format!("b\"{}\"", bulk_cm_name);
    let wrap_name = format!("{}_bulk_cm_wrap", entry.registry_key);

    let mut out = String::new();

    // cache_sym! for the bulk symbol.
    out.push_str(&format!(
        "cache_sym! {{\n    pub static {sym_name}: fn(usize, usize, &[CmTypes]) -> CmTypes = {sym_bytes};\n}}\n"
    ));

    // Trivial passthrough wrapper — no extraction, just forward.
    out.push_str(&format!(
        "pub fn {wrap_name}(start: usize, end: usize, args: &[CmTypes]) -> CmTypes {{\n"
    ));
    out.push_str(&format!("    {sym_name}(start, end, args)\n"));
    out.push_str("}\n");

    out
}

fn build_rust_sym_call(entry: &ExportedFn, variadic_idx: Option<usize>) -> String {
    let sym_name = sym_static_name(&entry.cm_name);

    let args: Vec<String> = entry
        .cm_params
        .iter()
        .enumerate()
        .map(|(i, p)| match &p.kind {
            CmParamKind::CmTypesRef => format!("&args[{}]", i),
            CmParamKind::Primitive(_) => p.name.clone(),
            CmParamKind::StrRef => p.name.clone(),
            CmParamKind::OwnedString => p.name.clone(),
            CmParamKind::VecCmTypes => format!("&{}", p.name),
            CmParamKind::SliceCmTypes => format!("&args[{}..]", i),
            CmParamKind::OpaquePtr
            | CmParamKind::ArrayPtr { .. }
            | CmParamKind::MutArrayPtr { .. } => unreachable!("C-only kinds in Rust entry"),
        })
        .collect();

    let _ = variadic_idx; // already handled in args above

    format!("{}({})", sym_name, args.join(", "))
}

// ---------------------------------------------------------------------------
// C entry wrapper rendering
// ---------------------------------------------------------------------------

/// Render the `cache_sym!` + `_wrap` function for a C-sourced entry.
fn render_c_entry_wrapper(entry: &ExportedFn) -> String {
    let sym_name = sym_static_name(&entry.cm_name);
    let sym_type = build_c_sym_type(entry);
    let sym_bytes = format!("b\"{}\\0\"", entry.cm_name);
    let wrap_name = wrap_fn_name(&entry.cm_name);
    let fn_name_str = &entry.cm_name;

    let mut out = String::new();

    // Main cache_sym!
    out.push_str(&format!(
        "cache_sym! {{\n    pub static {sym_name}: {sym_type} = {sym_bytes};\n}}\n"
    ));

    // Free-function cache_sym! if any ret variant needs one
    let free_fn_opt: Option<String> = match &entry.cm_ret {
        CmRet::AllocatedArray { free_fn, .. } => free_fn.clone(),
        CmRet::AllocatedString { free_fn } => free_fn.clone(),
        _ => None,
    };
    if let Some(ref free_fn) = free_fn_opt {
        let free_sym_name = format!("{}_SYM", free_fn.to_uppercase());
        let free_sym_bytes = format!("b\"{}\\0\"", free_fn);
        out.push_str(&format!(
            "cache_sym! {{\n    static {free_sym_name}: unsafe extern \"C\" fn(*mut c_void) = {free_sym_bytes};\n}}\n"
        ));
    }

    // _wrap function
    out.push_str(&format!(
        "pub fn {wrap_name}(args: &[CmTypes]) -> CmTypes {{\n"
    ));

    // Find the variadic param index (SliceCmTypes)
    let variadic_idx = entry
        .cm_params
        .iter()
        .position(|p| matches!(p.kind, CmParamKind::SliceCmTypes));

    // Track which CmTypes arg index we are consuming.
    // auto_params are NOT consumed from args.
    let mut arg_idx: usize = 0;

    // For MutArrayPtr params we embed the call inline; track if that's needed.
    let mut mut_array_param: Option<(usize, &CmParam)> = None; // (arg_idx, param)

    // First pass: classify params and emit extractions for non-MutArrayPtr ones.
    // We need to collect all extractions before emitting the call.
    struct ParamExtraction {
        /// Lines to emit before the call.
        pre_lines: Vec<String>,
        /// The argument expression(s) to pass to the C function.
        /// For ArrayPtr this is two expressions: ptr + len.
        call_args: Vec<String>,
        /// Whether this is a MutArrayPtr (call is embedded in with_any_mut closure).
        is_mut_array: bool,
    }

    let mut extractions: Vec<ParamExtraction> = Vec::new();

    for param in &entry.cm_params {
        let is_auto = entry.auto_params.contains(&param.name);
        if is_auto {
            // This param is auto-derived; it doesn't consume a CmTypes arg.
            // Its value is synthesized from the companion ArrayPtr param.
            // We skip it here — the len variable is emitted as part of the ArrayPtr extraction.
            continue;
        }

        let cur_arg_idx = arg_idx;

        match &param.kind {
            CmParamKind::Primitive(pk) => {
                let variant = pk.variant_name();
                let rt = pk.rust_type();
                let pre = format!(
                    "    let {name} = match args[{cur_arg_idx}] {{ CmTypes::{variant}(x) => x as {rt}, _ => panic!(\"{fn_name_str}: expected {variant} for {name}\") }};",
                    name = param.name
                );
                extractions.push(ParamExtraction {
                    pre_lines: vec![pre],
                    call_args: vec![param.name.clone()],
                    is_mut_array: false,
                });
                arg_idx += 1;
            }
            CmParamKind::StrRef => {
                let name = &param.name;
                let pre1 = format!(
                    "    let {name}_s = match &args[{cur_arg_idx}] {{ CmTypes::String(x) => x.to_string(), _ => panic!(\"{fn_name_str}: expected String for {name}\") }};"
                );
                let pre2 = format!(
                    "    let {name}_c = CString::new({name}_s).unwrap_or_else(|_| CString::new(\"\").unwrap());"
                );
                extractions.push(ParamExtraction {
                    pre_lines: vec![pre1, pre2],
                    call_args: vec![format!("{name}_c.as_ptr()")],
                    is_mut_array: false,
                });
                arg_idx += 1;
            }
            CmParamKind::OpaquePtr => {
                let name = &param.name;
                let pre = format!(
                    "    let {name}_ptr = args[{cur_arg_idx}].with_any(|h: &OpaqueHandle| h.0).unwrap_or_else(|| panic!(\"{fn_name_str}: expected OpaqueHandle for {name}\"));"
                );
                extractions.push(ParamExtraction {
                    pre_lines: vec![pre],
                    call_args: vec![format!("{name}_ptr")],
                    is_mut_array: false,
                });
                arg_idx += 1;
            }
            CmParamKind::ArrayPtr {
                len_param,
                c_element_type,
            } => {
                let name = &param.name;
                let len = len_param.clone();
                let rt = c_elem_rust_type(c_element_type);
                let pre = format!(
                    "    let ({name}_ptr, {len}) = args[{cur_arg_idx}].with_any(|v: &Vec<{rt}>| (v.as_ptr() as *const c_void, v.len())).unwrap_or_else(|| panic!(\"{fn_name_str}: expected Vec<{rt}> for {name}\"));"
                );
                extractions.push(ParamExtraction {
                    pre_lines: vec![pre],
                    call_args: vec![format!("{name}_ptr"), len],
                    is_mut_array: false,
                });
                arg_idx += 1;
            }
            CmParamKind::MutArrayPtr {
                len_param,
                c_element_type,
            } => {
                let name = &param.name;
                let len = len_param.clone();
                let rt = c_elem_rust_type(c_element_type);
                // Emit a len extraction first; the actual call is embedded in with_any_mut.
                let pre = format!(
                    "    let {len} = args[{cur_arg_idx}].with_any(|v: &Vec<{rt}>| v.len()).unwrap_or_else(|| panic!(\"{fn_name_str}: expected Vec<{rt}> for {name}\"));"
                );
                extractions.push(ParamExtraction {
                    pre_lines: vec![pre],
                    call_args: vec!["v.as_mut_ptr() as *mut c_void".to_string(), len],
                    is_mut_array: true,
                });
                mut_array_param = Some((cur_arg_idx, param));
                arg_idx += 1;
            }
            CmParamKind::SliceCmTypes => {
                let vi = cur_arg_idx;
                let pre1 = format!(
                    "    let mut __handles: Vec<*mut c_void> = Vec::with_capacity(args.len().saturating_sub({vi}));"
                );
                let pre2 = format!(
                    "    for __arg in &args[{vi}..] {{ let __ptr = __arg.with_any(|h: &OpaqueHandle| h.0).unwrap_or_else(|| panic!(\"{fn_name_str}: variadic: expected OpaqueHandle\")); __handles.push(__ptr); }}"
                );
                extractions.push(ParamExtraction {
                    pre_lines: vec![pre1, pre2],
                    call_args: vec![
                        "__handles.as_ptr()".to_string(),
                        "__handles.len()".to_string(),
                    ],
                    is_mut_array: false,
                });
                // variadic consumes remaining args — don't increment further
                arg_idx = usize::MAX; // sentinel: no more params after this
            }
            CmParamKind::CmTypesRef | CmParamKind::OwnedString | CmParamKind::VecCmTypes => {
                unreachable!("Rust-only kinds in C entry");
            }
        }
    }

    // Emit all pre-lines
    for ext in &extractions {
        for line in &ext.pre_lines {
            out.push_str(line);
            out.push('\n');
        }
    }

    // Collect all call_args (flat)
    let all_call_args: Vec<String> = extractions
        .iter()
        .flat_map(|e| e.call_args.iter().cloned())
        .collect();

    // Determine if any param is MutArrayPtr (call embedded in closure)
    let has_mut_array = extractions.iter().any(|e| e.is_mut_array);

    if has_mut_array {
        // Find the MutArrayPtr param index
        let (mut_arg_idx, mut_param) = mut_array_param.unwrap();
        let mut_name = &mut_param.name;
        let (len_param_name, mut_rt) = match &mut_param.kind {
            CmParamKind::MutArrayPtr {
                len_param,
                c_element_type,
            } => (len_param.clone(), c_elem_rust_type(c_element_type)),
            _ => unreachable!(),
        };

        // Build call args excluding the MutArrayPtr's own contribution
        // (v.as_mut_ptr() and len are injected by the closure)
        let mut call_args_for_closure: Vec<String> = Vec::new();
        for ext in extractions.iter() {
            if ext.is_mut_array {
                // These come from the closure signature
                call_args_for_closure.push("v.as_mut_ptr() as *mut c_void".to_string());
                call_args_for_closure.push(len_param_name.clone());
            } else {
                for a in &ext.call_args {
                    call_args_for_closure.push(a.clone());
                }
            }
        }

        let call_expr = format!("(*{sym_name})({})", call_args_for_closure.join(", "));

        out.push_str(&format!(
            "    args[{mut_arg_idx}].with_any_mut(|v: &mut Vec<{mut_rt}>| {{\n"
        ));
        out.push_str(&format!("        unsafe {{ {call_expr}; }}\n"));
        out.push_str("    }).unwrap_or_else(|| panic!(\"");
        out.push_str(fn_name_str);
        out.push_str(": expected Vec<[f32;2]> for ");
        out.push_str(mut_name);
        out.push_str("\"));\n");
        out.push_str("    CmTypes::None\n");
    } else {
        // Normal call
        let call_expr = format!("(*{sym_name})({})", all_call_args.join(", "));

        let _ = variadic_idx;

        match &entry.cm_ret {
            CmRet::Void => {
                out.push_str(&format!("    unsafe {{ {call_expr}; }}\n"));
                out.push_str("    CmTypes::None\n");
            }
            CmRet::Primitive(pk) => {
                let variant = pk.variant_name();
                out.push_str(&format!("    let __result = unsafe {{ {call_expr} }};\n"));
                out.push_str(&format!("    CmTypes::{variant}(__result)\n"));
            }
            CmRet::OpaquePtr => {
                out.push_str(&format!("    let __raw = unsafe {{ {call_expr} }};\n"));
                out.push_str("    CmTypes::from_any(OpaqueHandle(__raw))\n");
            }
            CmRet::AllocatedArray {
                c_element_type,
                len_from_param,
                free_fn,
            } => {
                let rt = c_elem_rust_type(c_element_type);
                out.push_str(&format!(
                    "    let __raw = unsafe {{ {call_expr} }} as *const {rt};\n"
                ));
                out.push_str(&format!(
                    "    let __vec: Vec<{rt}> = unsafe {{ std::slice::from_raw_parts(__raw, {len_from_param}) }}.to_vec();\n"
                ));
                if let Some(ref ff) = free_fn {
                    let free_sym = format!("{}_SYM", ff.to_uppercase());
                    out.push_str(&format!(
                        "    unsafe {{ (*{free_sym})(__raw as *mut c_void) }};\n"
                    ));
                }
                out.push_str("    CmTypes::from_any(__vec)\n");
            }
            CmRet::AllocatedString { free_fn } => {
                out.push_str(&format!(
                    "    let __raw = unsafe {{ {call_expr} }} as *const std::ffi::c_char;\n"
                ));
                out.push_str(
                    "    let __s = unsafe { CStr::from_ptr(__raw) }.to_string_lossy().into_owned();\n",
                );
                if let Some(ref ff) = free_fn {
                    let free_sym = format!("{}_SYM", ff.to_uppercase());
                    out.push_str(&format!(
                        "    unsafe {{ (*{free_sym})(__raw as *mut c_void) }};\n"
                    ));
                }
                out.push_str("    CmTypes::String(std::sync::Arc::from(__s.as_str()))\n");
            }
            CmRet::CmTypes | CmRet::OwnedString => {
                unreachable!("Rust-only return kinds in C entry")
            }
        }
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Rendering func_reg.rs
// ---------------------------------------------------------------------------

fn render_registry(entries: &[ExportedFn]) -> String {
    let mut out = String::new();
    out.push_str("use crate::wrappers::*;\n");
    out.push_str("use tomii_types::*;\n\n");
    out.push_str("pub fn get_func(func_name: &str) -> Option<CmPtr> {\n");
    out.push_str("    match func_name {\n");

    for entry in entries {
        let key = &entry.registry_key;
        let wrap_fn = wrap_fn_name(&entry.cm_name);
        out.push_str(&format!("        \"{key}\" => Some({wrap_fn}),\n"));
    }

    out.push_str("        _ => {\n");
    out.push_str("            println!(\"Function {} not found in registry\", func_name);\n");
    out.push_str("            panic!(\"Function not found: {}\", func_name);\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Emit get_bulk_func only when at least one entry has a bulk companion.
    out.push_str("pub fn get_bulk_func(func_name: &str) -> Option<CmBulkPtr> {\n");
    out.push_str("    match func_name {\n");

    for entry in entries {
        if entry.has_bulk_cm && entry.source_lang == SourceLang::Rust {
            let key = &entry.registry_key;
            let bulk_wrap_fn = format!("{}_bulk_cm_wrap", key);
            out.push_str(&format!("        \"{key}\" => Some({bulk_wrap_fn}),\n"));
        }
    }

    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prim_kind_usize() {
        let kind = prim_kind_from_str("usize");
        assert!(matches!(kind, Some(PrimKind::Usize)));
    }

    #[test]
    fn test_classify_no_mangle_cm() {
        let src = r#"
            #[no_mangle]
            pub fn generate_vector_cm(n: usize) -> CmTypes { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        assert_eq!(e.cm_name, "generate_vector_cm");
        assert_eq!(e.registry_key, "generate_vector");
        assert_eq!(e.cm_params.len(), 1);
        assert!(matches!(
            e.cm_params[0].kind,
            CmParamKind::Primitive(PrimKind::Usize)
        ));
        assert!(matches!(e.cm_ret, CmRet::CmTypes));
        assert_eq!(e.source_lang, SourceLang::Rust);
    }

    #[test]
    fn test_classify_tomii_export() {
        let src = r#"
            #[tomii_export]
            pub fn compute_fft(fft_planner: &SomePlanner, buffer: &mut SomeBuf) { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        assert_eq!(entries.len(), 1);
        let e = &entries[0];
        assert_eq!(e.cm_name, "compute_fft_cm");
        assert_eq!(e.registry_key, "compute_fft");
        // Both non-primitive refs → CmTypesRef
        assert!(matches!(e.cm_params[0].kind, CmParamKind::CmTypesRef));
        assert!(matches!(e.cm_params[1].kind, CmParamKind::CmTypesRef));
        // void return
        assert!(matches!(e.cm_ret, CmRet::CmTypes));
        assert_eq!(e.source_lang, SourceLang::Rust);
    }

    #[test]
    fn test_str_param() {
        let src = r#"
            #[no_mangle]
            pub fn get_out_file(env_var: &str, out_file: &str) -> String { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        let e = &entries[0];
        assert_eq!(e.cm_name, "get_out_file");
        assert_eq!(e.registry_key, "get_out_file");
        assert!(matches!(e.cm_params[0].kind, CmParamKind::StrRef));
        assert!(matches!(e.cm_params[1].kind, CmParamKind::StrRef));
        assert!(matches!(e.cm_ret, CmRet::OwnedString));
    }

    #[test]
    fn test_vec_cmtypes_param() {
        let src = r#"
            #[no_mangle]
            pub fn write_to_file(file_path: &str, buffers: &Vec<CmTypes>) { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);
        let e = &entries[0];
        assert_eq!(e.cm_name, "write_to_file");
        assert!(matches!(e.cm_params[0].kind, CmParamKind::StrRef));
        assert!(matches!(e.cm_params[1].kind, CmParamKind::VecCmTypes));
    }

    /// Regression: when `wf_cell` and `wf_cell_bulk` coexist, the per-cell
    /// companion `wf_cell_bulk_cm` (generated for `wf_cell_bulk`) must NOT be
    /// mistaken for the bulk companion of `wf_cell`.
    #[test]
    fn test_no_bulk_collision_between_wf_cell_and_wf_cell_bulk() {
        // Simulate the macro-generated output for both functions.
        // `wf_cell_cm` is the per-cell companion for `wf_cell`.
        // `wf_cell_bulk_cm` is the per-cell companion for `wf_cell_bulk`.
        // `wf_cell_bulk_bulk_cm` is the true bulk companion for `wf_cell_bulk`.
        let src = r#"
            #[tomii_export]
            pub fn wf_cell(grid: &Vec<f64>, n: usize, diag: usize, idx: usize) {}

            #[tomii_export(bulk)]
            pub fn wf_cell_bulk(grid: &Vec<f64>, n: usize, diag: usize, idx: usize) {}

            #[no_mangle]
            pub fn wf_cell_cm(grid: &CmTypes, n: usize, diag: usize, idx: usize) -> CmTypes { todo!() }

            #[no_mangle]
            pub fn wf_cell_bulk_cm(grid: &CmTypes, n: usize, diag: usize, idx: usize) -> CmTypes { todo!() }

            #[no_mangle]
            pub fn wf_cell_bulk_bulk_cm(start: usize, end: usize, args: &[CmTypes]) -> CmTypes { todo!() }
        "#;
        let file: File = parse_str(src).unwrap();
        let entries = collect_entries(&file);

        // We expect entries for the two tomii_export functions plus the three no_mangle companions.
        // The tomii_export entries should be: wf_cell (no bulk), wf_cell_bulk (has bulk).
        let wf_cell_entry = entries.iter().find(|e| e.registry_key == "wf_cell" && e.cm_name == "wf_cell_cm");
        let wf_cell_bulk_entry = entries.iter().find(|e| e.registry_key == "wf_cell_bulk" && e.cm_name == "wf_cell_bulk_cm");

        assert!(wf_cell_entry.is_some(), "wf_cell entry not found");
        assert!(wf_cell_bulk_entry.is_some(), "wf_cell_bulk entry not found");

        // wf_cell must NOT have a bulk companion (collision guard).
        assert!(!wf_cell_entry.unwrap().has_bulk_cm, "wf_cell falsely detected as having bulk companion");

        // wf_cell_bulk MUST have a bulk companion.
        assert!(wf_cell_bulk_entry.unwrap().has_bulk_cm, "wf_cell_bulk bulk companion not detected");
    }
}
